### ISSUE TITLE
Are all clients required to call PMIx_Init?

### ISSUE THREAD

**Issue by dsolt** [pmix/pmix-standard#10]
If I launch an application with 10 ranks.  Is it valid for only one of those ranks/procs to call PMIx_Init and make additional PMIx calls.   If so, can it call PMIx_Get() on a proc that never called PMIx_Init()?

Also, in general as we write this, do we refer to ranks or procs or pmix_proc_t's or how do you refer to a single client process (just for uniformity)

**Comment by rhc54** [comment]
The rule we've operated under is that if any process in an nspace calls PMIx_Init, then they all must do so or else we consider that an "abnormal" termination when one of them exits. In the scenario you described, the caller would hang because (a) PMIx_Get is a blocking call, and (b) the other process never provided the information. Note that the second process simply calling PMIx_Init is not sufficient to resolve the hang - it must PMIx_Put and PMIx_Commit the requested information.

Which is why the PMIX_TIMEOUT attribute was created 😄 

I normally refer to procs myself, but I'm open to suggestion. I tend to stay away from "ranks" as it generates a reaction from the MPI crow. Single client process is a "proc". I reserve the term client to designate a proc that is connected to a server - i.e., when I talk about a client, I mean a proc that is connected to me.

**Comment by jjhursey** [comment]
Per teleconf: We need a note in the initialization chapter.

From PMIx library perspective there is no requirement that all processes in the namespace call `PMIx_Init`. It should be noted in the PMIx standard that if not all processes in the namespace do call `PMIx_Init` then some interfaces will hang (or timeout if an attribute is passed). The user should be careful of operations that may not complete (fence) since not all are participating. Locally completing functions, and get operations on job data should be fine. Does the PMIx standard need to enumerate this list or can we craft some general terms?

ORTE currently requires all or none to call `PMIx_Init`, but that's a RM specific restriction.

Follow on question:
 - Can some processes in the namespace call different PMIx initialization routines (`PMIx_tool_init` in process 0 and `PMIx_init` in process 1). I think we should add the restriction that everyone in the namespace must call the same form of initialization.
 - Is it ever useful for a PMIx process to be both a 'tool' and a 'client' at the same time? I don't think so. Do we want to add an advice to users about this scenario.
 - Same for the 'client' and 'server' in the same process. Maybe add a restriction on this.

**Comment by rhc54** [comment]
> Does the PMIx standard need to enumerate this list or can we craft some general terms?

I think we'll need to enumerate it else we generate a lot of support emails

> Can some processes in the namespace call different PMIx initialization routines (PMIx_tool_init in process 0 and PMIx_init in process 1). I think we should add the restriction that everyone in the namespace must call the same form of initialization.

Agreed - we definitely cannot handle the mixed case.

> Is it ever useful for a PMIx process to be both a 'tool' and a 'client' at the same time? I don't think so. Do we want to add an advice to users about this scenario.

Actually, yes - a debugger tool needs access to the client APIs such as query and get. We currently automatically do so.

> Same for the 'client' and 'server' in the same process. Maybe add a restriction on this.

Ditto here - the server actually does need access to client APIs. Note that we now have the scenario where a server in an mpirun-spawned daemon needs to contact the RM-based daemon via PMIx to request services - and so the "orted" winds up looking like both a client and a server. Sigh.

**Comment by jjhursey** [comment]
It looks like Ralph already put clarification to this point in the initialization chapter.
@rhc54 Do we need any further clarification or can this ticket be closed?

**Comment by rhc54** [comment]
I think we are good.
