### ISSUE TITLE
Mention of PMIX_USERID info key in server init and namespace registration sections

### ISSUE THREAD

**Issue by artpol84** [pmix/pmix-standard#122]
This info key is [currently passed](https://github.com/SchedMD/slurm/blob/master/src/plugins/mpi/pmix/pmixp_client_v2.c#L234) through the info keys by Slurm at the PMIx_Server_init call. In the PMIx/dstor we also implemented a possibility of doing this on per-namespace basis for RM's that are utilizing multi-session mode.

The rationale for Slurm is that slurmd's are running partially as root and partially as slurm user. For the dstor that creates shmem files it is necessary to know user ID in order to properly set permissions on those files.

I also can see the value of this for other RM's running as user != to the application users.

This should be an optional parameter for both server init and namespace registration calls.

**Comment by artpol84** [comment]
I'm OK with doing it myself, but wanted to have a ticket to see if others are ok with this.

**Comment by rhc54** [comment]
I'm trying to get a clear understanding of what you propose. The Slurm entity must do a ```setuserid``` to the proper user at time of fork/exec (root or slurm user). It therefore doesn't seem necessary to pass the userid to the PMIx server - it can just get it with ```geteuserid```. Indeed, passing a userid seems risky from a security standpoint as you could be passed a userid that is different from the one the process set itself to be.

This leaves the question of the effective userid of the client process as the dstor needs to set proper permissions on the shmem files. The way we are currently setup in the PMIx server, the shmem files are not created until we receive the initial connection from a local client from that namespace. Part of the connection protocol involves the client passing its effective userid and grpid - we do this because the client process could have changed those after it was exec'd. Still no guarantee they won't change it again after calling PMIx_Init, but we can't do much about that scenario. Thus, the dstor can simply access the effective id's of the client by looking at the pmix_peer_t object.

Given that analysis, I don't see the reason behind passing PMIX_USERID - indeed, it would seem to open the door to errors, yes?

**Comment by rhc54** [comment]
> No it cannot as PMIx server is part of slurmstepd which is not running as application user. so getruserid will not return ID of the application user.

I agree - my point was that the PMIx server always knows its userid and doesn't need to be told it. I read your original note as suggesting that you were (among other things) telling the PMIx server its ID as you passed PMIX_USERID to the server during server_init:

> This info key is currently passed through the info keys by Slurm at the PMIx_Server_init call.

My comment was that this isn't necessary and may not be good practice.

> In my understanding Slurm being RM knows what user supposed to run the application.

I believe your understanding is incorrect. Slurm knows the userid of the user that submitted the job, and there is a baseline assumption/contract that this will be the userid when the job is started. However, there is no guarantee that the application won't change effective userid, or effective groupid. The latter is frequently used, for example, to control billing of specific parts of the application's execution as many organizations equate groupid with billing number.

>  Indeed getting this information from the connected process seems dangerous to me as it might be a malicious one.

Agreed - which is why we stipulate that the RM _must_ take responsibility for authenticating and authorizing the application, and why we report the effective user/group ID's as we detect them using standard POSIX utilities. We specifically do _not_ allow the user to tell us what userid they would like to declare. Not perfect, but at least we know that the system allowed the user to set whatever userid we see, and the RM has the right to use something deeper if desired.

**Comment by artpol84** [comment]
> Agreed - which is why we stipulate that the RM must take responsibility for authenticating and authorizing the application, and why we report the effective user/group ID's as we detect them using standard POSIX utilities. We specifically do not allow the user to tell us what userid they would like to declare.

That sound reasonable. Can you point me to the API that declares that? I'd expect it to be through client connected call:
```C
typedef pmix_status_t (*pmix_server_client_connected_fn_t)(const pmix_proc_t *proc, void* server_object,  pmix_op_cbfunc_t cbfunc, void *cbdata)
```
But I don't see it there.

I see that PMIx passes PMIX_USERID and PMIX_GRPID to the Publish/lookup stuff though.

**Comment by artpol84** [comment]
@rhc54 could you provide some summary on this?
Why do we close it? 
Were any steps taken? If so - what is a reference to the standard change?

**Comment by rhc54** [comment]
Sorry - I thought I had verbally explained this to you. Let me recap it here.

We do not pass upward the uid/gid of the connecting client as it is unnecessary information. Clients _must_ be preregistered with the PMIx server library via the ```PMIx_server_register_client``` before they are spawned. That API requires that you pass the expected uid/gid of the client process.

When the client attempts to connect to the PMIx server, the server uses standard Linux methods to determine the effective uid/gid of the process requesting the connection. We do _not_ rely on anything the client process tells us as that would be unsafe. The effective uid/gid reported by the OS is compared to the values provided by the host - if they don't match, we drop the connection request.

Assuming the requesting client passes that test, we then proceed to execute the active security handshake. If the client passes that test, _then_ we report "client connected" to the host, which is free to do whatever else it wants at that point.

The reason for this procedure is to ensure that we do not allow a connection from a client that doesn't at least meet some minimal security requirements. You never want to allow a process to complete a socket connection to you and then decide "oops - we shouldn't be talking to you" - best to drop it as early as possible.

Tools are a different story as they may not have been started by the host. In that case, we use the standard Linux methods to get the effective uid/gid and report them upwards with the "tool connected" interface because there isn't anything else we can do. This leaves a security risk, which is why our server doesn't enable tool connections by default - the host has to explicitly enable them, recognizing the associated risk.

HTH

**Comment by rhc54** [comment]
Please see https://github.com/pmix/pmix-standard/pull/133 - tried to capture the above explanation.
