### ISSUE TITLE
Understanding the use of PMIx_server_setup_application

### ISSUE THREAD

**Issue by krempel-pt** [pmix/pmix-standard#157]
Hello,

this is a question on PMIx v3.0.

In section 11.1.9 PMIx_server_setup_application in line 14 on page 243 I read
> The returned data must be distributed by the RM and subsequently delivered to the local PMIx server on each node where application processes will execute, prior to initiating execution of those processes."

And in section 11.1.10 PMIx_server_setup_local_support in line 28 on page 244 I read
> "The data provided in the info array is the data provided to there host RM from the a call to PMIx_server_setup_application .

I do not understand what this exactly means. Shall I call the function once for each application running processes on the node, then distribute the returned data to all nodes where processes of the application will run and there merge and pass it to the PMIx server library with the call to PMIx_server_setup_local_support?

If I am right so far, according to the attributes PMIx_server_setup_application is required to support,
pmix_setup_application_cbfunc_t can return environment variables and other data. How can I distinguish between those types?
And do I have to set the environment variables for all processes of the application and only pass the other data to the PMIx servers?
Or is all that the purpose of PMIx_server_setup_local_support?

I think it would be good to clarify that a little more in the standard document, too.

Thank you.

**Comment by rhc54** [comment]
Welcome! I understand the confusion - I'm in the early stages of writing an entire new chapter of the standard to explain this process in detail. However, that is unlikely to be available for another month or so.

Here is a brief explanation in the interim. Let's assume for now that we are doing a direct launch - i.e., there is no use of an indirect launcher such as mpiexec. Instead, the host environment is going to use its daemons on the compute nodes to directly start the application processes. The indirect case isn't any different - just replace "scheduler" with "mpiexec" and the host environment's daemons with those launched by "mpiexec".

When the scheduler allocates resources for the job, it creates a map of which application processes are going to be executed on each node. Once it has this map, it passes it to the PMIx_server_setup_application function. The PMIx server library provides the map to its internal fabric plugins for processing. Each plugin can specify environmental params that need to be forwarded and can allocate network resources (e.g., sockets for messaging endpoints) for each process in the application. This only gets called once per job.

The PMIx_server_setup_application returns a "blob" containing all the information collected by the fabric plugins. This may or may not include envars - it is totally up to each plugin. The "blob" is to be included in the launch message the scheduler sends to its daemon on each compute node in the allocation. Note that the scheduler doesn't need to know anything about what is in the blob, nor does it have access to that detail.

Once the launch message arrives, each compute node daemon parses it according to whatever mechanism is used by that environment. This will retrieve the "blob" provided by PMIx_server_setup_application - that blob is then passed down into the PMIx_server_setup_local_support function for processing. Again, because there is one launch message for each job being executed, this call will occur once per job.

The PMIx server library in the compute node daemon passes the blob to its fabric plugins for processing. Each plugin extracts the information contributed by its cousin in the scheduler. If envars were captured, then the plugin hangs onto those. This is also where the local fabric driver can be loaded with a per-process connection table, or whatever else the fabric plugin wants to do. This can be done before or after the call to PMIx_server_register_nspace and/or PMIx_server_register_client - the ordering makes no difference.

Prior to starting each local process of the job, the compute node daemon calls PMIx_server_setup_fork. This in turn cycles thru the fabric plugins, giving each one an opportunity to contribute its envars. The compute node daemon adds the values returned by PMIx_server_setup_fork to the environment of the app process prior to fork/exec.

Remember, the compute node daemon is also required to call PMIx_server_register_nspace prior to starting the first local process of that job, and PMIx_server_register_client for each local process prior to starting it. These operations need to be done prior to calling PMIx_server_setup_fork.

Hope that helps!

**Comment by krempel-pt** [comment]
Thank you for the detailed explanation.

Just two questions remaining:
1. Is the PMIx_server_setup_application to be called once per job or once per application? I wonder because of the naming that implies per application, but the obvious identifier is the namespace? Do I have to call it once per application and pass PMIX_APPNUM in the info field?

2. I understand, that intentionally, PMIx_server_setup_application is called once on the node that initiates the launch and PMIx_server_setup_local_support is then called once at each node involved before PMIx_server_setup_fork is called for each client on that node. In my environment mpiexec spawns the PMIx server daemons only on the nodes where the job processes will run. Can I do the call to PMIx_server_setup_application just on the node where rank 0 will be spawned?
Until now, I did not care much about PMIx plugins, and perhaps I never have to, but I would like to implement the PMIx support as future proof as possible.

Thanks again.

**Comment by rhc54** [comment]
> Is the PMIx_server_setup_application to be called once per job or once per application? I wonder because of the naming that implies per application, but the obvious identifier is the namespace? Do I have to call it once per application and pass PMIX_APPNUM in the info field?

I fear the name is a little misleading - it is once per job. I'll try to add some clarifying text in the document, and be sure to address it more fully in the new chapter. The requirement is that you pass in a complete description of where all processes in the job will be executing - i.e., what node each process will be on.

> I understand, that intentionally, PMIx_server_setup_application is called once on the node that initiates the launch and PMIx_server_setup_local_support is then called once at each node involved before PMIx_server_setup_fork is called for each client on that node. In my environment mpiexec spawns the PMIx server daemons only on the nodes where the job processes will run. Can I do the call to PMIx_server_setup_application just on the node where rank 0 will be spawned?

Since mpiexec is usually the one that is determining the location of the processes, you will probably want to do the call to PMIx_server_setup_application from within mpiexec. You can then include the returned blob in the message mpiexec sends to its daemons telling them what to spawn, and where.

> Until now, I did not care much about PMIx plugins, and perhaps I never have to, but I would like to implement the PMIx support as future proof as possible.

Kewl. At the moment, we only have plugins that support Intel OmniPath (just to harvest and forward envars) and the harvesting/forwarding of PMIx_MCA params. Hopefully, we will see that expand this year as more fabric providers begin to contribute their plugins.

**Comment by rhc54** [comment]
Updated the prior comment to note that we also setup security keys for OmniPath.

**Comment by rhc54** [comment]
I've made some minor adjustments to the text - trying to avoid delaying until we write the new chapter that details this procedure. One change worth mentioning:
```
Host environments are required to execute this operation prior to launching a job. In
addition to supported directives, the info array must include a description of the job
using the PMIX_NODE_MAP and PMIX_PROC_MAP attributes.
```
I wouldn't worry about providing those right now as the support in PRI isn't complete yet. However, looking to the future, you will need to provide those when we release PRI v4.0.x. If you want to supply them today, then you can use the output of PMIx_generate_regex and PMIx_generate_ppn to provide those values.

I should note that we are probably going to deprecate those two regex functions in PMIx 4 and replace them with versions that return a pmix_info_t. We are experiencing some problems with regex generation/parsing due to a wide range of unexpected host name patterns and require some greater flexibility in handling them. Returning a pmix_info_t instead of a string allows us to use alternative mechanisms (e.g., compression algos, that don't return a POSIX-compatible string) when necessary. You'll still be able to use these until PMIx 5 comes out - this is just a "heads up".
