### ISSUE TITLE
Describing MCA params

### ISSUE THREAD

**Issue by rhc54** [pmix/pmix-standard#18]
Where/how do we want to capture MCA params? I'm looking at the PMIx server init procedure and the connection rendezvous support can be controlled via MCA param or info array. I can describe the attributes - but where do we communicate the corresponding MCA params and the precedence order?

**Comment by rhc54** [comment]
@jjhursey Any thoughts?

**Comment by jjhursey** [comment]
A thought:
 - Let's create a new section in the ... structures chapter maybe ... that describes each of the MCA parameters. Similar to how we treat attributes. The preamble to that section can describe the general precedence order, and any modifications to that order for a specific MCA parameter can be described at the MCA parameter definition.
 - I can create some LaTeX macros mirroring the attribute macros for MCA parameters. So we can copy/paste/extend. Then we can reference them throughout the document where needed.
 - Since we mark them differently than attributes, I can have LaTeX generate an appendix table listing all of the MCA parameters, and links to their definitions in the document. That might provide readers with an easy way to see what MCA options are available.

**Comment by rhc54** [comment]
Sold! Let me know when you have the macros ready and I will populate it

**Comment by rhc54** [comment]
Just to record what we decided: the MCA params don't belong in the standard. However, we will add an appendix to the document that contains PRL-specific features. In the case of MCA params, things are too fluid to put them in a document. What we will do in the Appendix is describe what these params are and how they are used (e.g., precedence algorithm) and include a pointer to the web site where we can more easily maintain a list of them.

Thus, there is no need for a macro to describe them.
