### ISSUE TITLE
Process Set Query Clarification

### ISSUE THREAD

**Issue by jjhursey** [pmix/pmix-standard#254]
During the Slices/Grouping Working Group meeting on July 8, 2020 we discussed the PMIx side of the MPI Sessions prototype in Open MPI. During that conversation we noted two items that needed to be adjusted in Ch. 13 "Process Sets and Groups"
 * Remove restriction in Ch. 13 of only 1 process set per proc. Processes may be multiple process sets.
 * When querying the process set names for a given process it is possible to get either:
   - A single string if it is in exactly one process set
   - An array of strings if it is in more than one process set

**Comment by jjhursey** [comment]
FYI: @rhc54 @spophale @SteVwonder @hppritcha

**Comment by rhc54** [comment]
Let me ask a simple question: should we coalesce the process "set" and process "group" concepts? If we provide an API by which one can add/remove procs from a "set", then we effectively have made a "set" to be the same as a "group". The only difference between them would be these things:
```latex
* Process groups are created in collective operations, even if the collective is
   asynchronous - i.e., the group is not considered formed until _all_ members
   have actively participated in the construct operation

* Process \emph{sets} have no implied relationship between their members - i.e., a
   process in a process set has no concept of a ``pset rank'' as it would in a
   process \emph{group}

* Process \emph{groups} can be used in calls to \ac{PMIx} operations. Members of
   process \emph{groups} that are involved in an operation are translated by their
   \ac{PMIx} server into their \emph{native} identifier prior to the operation being
   passed to the host environment. For example, an application can define a process
   group to consist of ranks 0 and 1 from the host-assigned namespace of
   \emph{210456}, identified by the group id of \emph{foo}. If the application
   subsequently calls the \refapi{PMIx_Fence} \ac{API} with a process identifier of
   \{foo, PMIX_RANK_WILDCARD\}, the \ac{PMIx} server will replace that identifier with
   an array consisting of \{210456, 0\} and \{210456, 1\} - the host-assigned identifiers
   of the participating processes - prior to passing the request up to the host environment

* Process \emph{groups} can request that the host environment assign a unique
   \code{size_t} \ac{PGCID} to the group at time of group construction. An \ac{MPI}
   library may, for example, use the \ac{PGCID} as the \ac{MPI} communicator identifier
   for the group.
```
From my perspective, the only real difference here is the first one - process set designations could be done by a central authority without the need for a collective operation. We can get away with that only because you cannot use a process set in a PMIx operation like you can do with a group ID because there is no guarantee that all the PMIx servers know the membership of the set without doing the collective.

But I'm not sure we can dynamically assign process set memberships without that collective guarantee. If a process queries the process set membership on a server that doesn't know about it yet, then it will get the wrong answer. So it seems to me that dynamically assigning process set memberships means that we must have a collective operation in that assignment to ensure that everyone knows about it...which means a "set" is essentially a "group".

Which brings me back to the initial question - given the request for dynamic set assignments, aren't these two concepts effectively the same? If so, then do we want to standardize on calling them "sets" or "groups"?

**Comment by rhc54** [comment]
@SteVwonder @spophale Please take a look at https://github.com/pmix/pmix-standard/pull/258 and see what you think. I have already asked @hppritcha and @jjhursey to review it as well.

**Comment by jjhursey** [comment]
@spophale Was working on this use case for the slices working group and might have some input on this proposal.

**Comment by rhc54** [comment]
Just to answer my own question about about keeping both "sets" and "groups": I spoke with @hppritcha about it and there is a need for both concepts. The key is what I tried to capture in the revisions: sets are defined by the host environment, while groups are defined by the application. So there is a critical difference between them and we do need to retain both classes. Applications are looking up set membership to identify who they want to "group" with.

**Comment by hppritcha** [comment]
@rhc54 right on with your above comment.
