### ISSUE TITLE
When exactly to return `PMIX_ERR_NOT_SUPPORTED` in `pmix_server_abort_fn_t`

### ISSUE THREAD

**Issue by krempel-pt** [pmix/pmix-standard#307]
Hello,

it is not clear to me for every case, how the host server using the support library needs to behave when `pmix_server_module_t.abort` is called.

If everything is supported, it is quiet clear:
- If `procs == NULL`, terminate all processes of the calling client's namespace and return `PMIX_OPERATION_SUCCEEDED` or directly return `PMIX_SUCCESS` and after terminating them call the callback function.
- If `procs != NULL` terminate the processes in the array and return `PMIX_OPERATION_SUCCEEDED` or directly return `PMIX_SUCCESS` and after terminating them call the callback function.

But there are some open questions:
- If `procs != NULL` but the host server is not able or not configured to terminate a subset of a namespace. Should it then return `PMIX_ERR_NOT_SUPPORTED` and do nothing or is it standard conform, too, to behave like `procs == NULL`, terminate the whole namespace and return PMIX_SUCCESS? 

This could be clarified in 16.3.5 as "Advice to PMIx server hosts" paragraph on when to return `PMIX_ERR_NOT_SUPPORTED` and which decisions on behavior are up to the host server.

- Is it allowed, that `procs` contains processes that are not in the namespace of the process calling `PMIx_Abort`?

This could be clarified in 11.1.1 or in 16.3.5 or both.

### References
4.0 draft:
- 16.3.5 `pmix_server_abort_fn_t`
- 11.1.1 `PMIx_Abort`

**Comment by rhc54** [comment]
You raise some good points. I wrestled with two possible responses for the edge cases you presented:

* return `PMIX_ERR_PARTIAL_SUCCESS` and terminate the procs that the host can terminate. I didn't really feel comfortable with this option as there is no way for the host to inform the caller as to which procs it terminated, and which are still executing.

* return `PMIX_ERR_BAD_PARAM` to indicate that the API itself is supported, but that the caller provided a parameter that lies outside of the ability of the host to support. In this case, the host would take no action - i.e., no processes would be aborted.

The second option appeared the better one to me, and so that is what I have proposed in the #308. I'd welcome your comments on that RFC.

**Comment by jjhursey** [comment]
It seems that the server should return `PMIX_ERR_NOT_SUPPORTED` and take no action in this case. The parameter is fine t pass to the API, but just not supported by the RM.

**Comment by rhc54** [comment]
Yeah, that is another approach - but it doesn't tell you where the issue lies. Is the API not supported somewhere? Is the parameter passed to the API the issue? Seems like we kinda leave the user in "whack-a-mole" mode.

Perhaps what we should do is add a `PMIX_ERR_ATTRIBUTE_NOT_SUPPORTED` or `PMIX_ERR_PARAM_VALUE_NOT_SUPPORTED` constant? Something that is more informative than "something you requested isn't supported, but we don't tell you what it might be".

**Comment by jjhursey** [comment]
I would prefer returning `PMIX_ERR_PARAM_NOT_SUPPORTED` (or something like that), then advise the user to consult the RM docs/logs for details. I don't know if they could use `PMIx_Query_info` to resolve this information, but maybe.

**Comment by krempel-pt** [comment]
I agree, that reporting `PMIX_ERR_BAD_PARAM` could lead to confusion. If I get this error back, I would assume that I did something that the API does not allow, passing NULL where not permitted or something like that. And I like the idea to split up the `PMIX_ERR_NOT_SUPPORTED` in more speaking subclasses like in this case `PMIX_ERR_PARAM_VALUE_NOT_SUPPORTED`.

I did not dive into `PMIx_Query_info` deeply yet, but if there was an interface to query the capabilities of the RM, that would be nice, I guess.

**Comment by rhc54** [comment]
You can indeed query the API/attribute support from the library as well as the host RM (assuming they registered it). However, for the case being requested here, the query really doesn't help. It would tell you that `PMIx_Abort` is supported by the client, server, and the host - but it cannot tell you that the host won't support termination of individual procs, or procs from another namespace.

We could, I suppose, ask that the host and library include all such limitations in the description they provide when they register their support for a given API - but that might get pretty wordy. Still, could be a solution.

Meantime, I'll update #308 with the new return constants - let's see what that would look like. We'd have to think about where those constants should go too - they might well need to be flagged on every API.

**Comment by jjhursey** [comment]
This was fixed in PR #308 and included in the v4.1 release.
