### ISSUE TITLE
Help understanding info's passed to pmix_server_dmodex_req_fn_t

### ISSUE THREAD

**Issue by dsolt** [pmix/pmix-standard#354]
This might have to be a @rhc54 question.   I see that pmix_server_dmodex_req_fn_t is called by the PMIx server library and it has an info and ninfo fields.   It is unclear what a RM should do with these fields.  For example, I'm seeing it called in one case with 2 infos:  pmix.req.key and pmix.node.info.   The RM forwards this request to the appropriate node where the RM calls PMIx_server_dmodex_request(const pmix_proc_t *proc, pmix_dmodex_response_fn_t cbfunc, void *cbdata).  However, there is no mechanism to pass the 2 info's provided into this call.  So I'm not sure how the RM is supposed to handle these.  The standard only calls out pmix.req.key as a required attribute, but it seems like the pmix server passed in pmix.node.info for a reason.  For the pmix.req.key, the RM can't even tell if the data returned has the required key.  It just gets back a "blob" of data, so its not like the RM can loop calling PMIx_server_dmodex_request repeatedly until the required attribute is returned.

Thoughts on how this is supposed to work and then maybe we can work on making the standard present it clearer?

### Suggested Clarification

I don't have a suggestion right now until I have a better idea of how it is supposed to work.

### References

17.3.7
17.2.10.1

**Comment by rhc54** [comment]
Hmmm...it looks like there may be a problem in the implementation, actually, if it is doing that - though I suppose someone might mistakenly call `PMIx_Get` with a non-reserved key and flag it as "node info". In the chapter on "reserved keys", we explicitly state that the server cannot request reserved keys from the host environment. Reserved keys can only be provided by the host during namespace registration (and updated via the same API). The dmodex request function, therefore, is solely for requesting non-reserved keys.

Thus, it makes no sense to pass a dmodex request that contains the `PMIX_NODE_INFO` attribute - the host would have no idea what to do with it as all "node info" are reserved keys, so the only option would be to ignore it (which is certainly what PRRTE would do). The only attributes the dmodex request should be able to support are things like "required key" and "timeout" that must be dealt with by the host (so no reason to pass anything down to the PMIx server library). I know we are checking this in the latest library to ensure that we never pass a reserved key request up to the host, but I honestly forget how far back we went with that change. We don't, however, check the attributes to see if someone mistakenly included "node info" (or one of its colleagues) for a non-reserved key - we just ignore it.

As for how to deal with the "required key" attribute, I can only tell you how PRRTE does it. We simply do a `PMIx_Get` to verify that the requested key is present, and then collect/return the "blob" once it is (if the "get" fails, we just do a timer and try again until we either find it or hit timeout). Pretty trivial thing to implement. As you say, there isn't a way to tell the PMIx server to "hold" the request until a particular key is available - we sadly hadn't adopted the "every API shall include an info array for attributes" rule yet when we created that API. 😞

**Comment by dsolt** [comment]
Ok, I am seeing a PMIX_NODE_INFO coming through (my client is a tool doing PMIX_Get on pmix.hname for a specific rank, so I'm not sure why that would result in that, but it appears to be.  Either way, that is an implementation issue that we can look into or not, but not really a standards issue. 

Having the server do a PMIx_Get to figure out when the data is there sounds like a reasonable solution.  I'm going to leave this issue open if that's ok for at least the next 2 weeks so we can discuss in our next working group call and decide if there should be any clarifying text added to the standard, but at least I get how it is works now.  Thanks!

**Comment by rhc54** [comment]
Sure, we can leave this open as long as you like. I'll take a peek at that example and see what's going on there.

**Comment by krempel-pt** [comment]
Just to give this a little push: I just struggled on exactly the same question how the RM should handle `pmix.req.key` info in `pmix_server_dmodex_req_fn_t`. So thanks for the explanation and my +1 for a clarifying sentence in the standard.

**Comment by krempel-pt** [comment]
I now implemented that and struggled on a connected issue: I'm was not yet able to write a program for testing that.

I would have expected, that `PMIx_get_nb()` with a remote rank and `PMIX_TIMEOUT` info leads to a call to `pmix_server_dmodex_req_fn_t()` with `PMIX_REQUIRED_KEYS` info set to a list containing the requested key as sole entry. But that is not the case. So the question is, what action of a client leads to  `PMIX_REQUIRED_KEYS` being set?

@rhc54 can you push me in the right direction once again, please?


I do have an additional point: During my test attempts, I tried to pass `PMIX_GET_REFRESH_CACHE` info to the `PMIx_Get_nb()` call. I don't know whether the flag i already handled by the openpmix, but it is passed to the host environment through `pmix_server_dmodex_req_fn_t()`, too. What is that meant for? Shall the host do something here or just ignore that info entry? In the second case, wouldn't it be better to filter out such info entries and only pass those relevant for the host environment?
(Asking that here, since it fits into the topic headline, too)

**Comment by krempel-pt** [comment]
Maybe I have to apologize for not investigating the problem deep enough. After taking another look into the openpmix code, I came to the conclusion that it at least tries to set `PMIX_REQUIRED_KEY` info. So deeper looking into the RM code and some debugging later, it turned out that the info is never shown anywhere, since this particular info entry somehow becomes messed up and then was silently ignored. It looks like the key entry in the info is already broken at the moment `pmix_server_dmodex_req_fn_t` is called, so I have to further investigate, how this can be.

The second question about `PMIX_GET_REFRESH_CACHE` remains.

**Comment by rhc54** [comment]
> I would have expected, that `PMIx_get_nb()` with a remote rank and `PMIX_TIMEOUT` info leads to a call to `pmix_server_dmodex_req_fn_t` with and `PMIX_REQUIRED_KEY` info set to the requested key. But that is not the case. So the question is, what action of a client leads to `PMIX_REQUIRED_KEY` being set?

Short answer is "it depends". If the key is a reserved key (i.e., one defined by the standard), then it will usually not be provided to the host for resolution. I say "usually" because it used to be "never", but I think we relaxed it a little bit recently as there are some keys that the host wouldn't provide at job start. I'd have to check. So if you were requesting info on a reserved key (outside of the relaxation), then the server will simply return "not found" if it isn't already present.

**Comment by rhc54** [comment]
> I do have an additional point: During my test attempts, I tried to pass `PMIX_GET_REFRESH_CACHE` info to the `PMIx_Get_nb()` call. I don't know whether the flag i already handled by openpmix, but it is passed to the host environment through `pmix_server_dmodex_req_fn_t`, too. What is that meant for? Shall the host do something here or just ignore that info entry? In the second case, wouldn't it be better to filter out such info entries and only pass those relevant for the host environment?
> (Asking that here, since it fits into the topic headline, too)

When the remote host daemon passes the dmodex request to its PMIx server, the server returns _all_ the non-local (i.e., remote or global) data posted by the specified process. This is done for optimization since if someone asks for one piece of info about a process, it is likely they will be asking for other pieces of info from that process. So we send it all back.

Some programming models, however, involve a process re-posting a key at a later time in the execution, usually with a changed value. Since the "old" version of the key is already locally known, the client has to tell PMIx to "refresh the cache". True, we could edit that directive out of what they provided before up-calling the host, but we chose not to do so because the host environment might have chosen to keep their own cache of data they retrieved from the PMIx server. This simply informs the host that we really do want them to re-query their PMIx server for the data.

If you don't retain your own cache, then you can simply ignore that directive (which is what PRRTE does). Otherwise, there is no harm passing it down in the dmodex request to the local PMIx server - it'll just be ignored.

**Comment by krempel-pt** [comment]
> > Maybe I have to apologize for not investigating the problem deep enough. After taking another look into the openpmix code, I came to the conclusion that it at least tries to set `PMIX_REQUIRED_KEY` info. So deeper looking into the RM code and some debugging later, it turned out that the info is never shown anywhere, since this particular info entry somehow becomes messed up and then was silently ignored. It looks like the key entry in the info is already broken at the moment `pmix_server_dmodex_req_fn_t` is called, so I have to further investigate, how this can be.
> 
> I'm not seeing that problem - we routinely test dmodex and I see it waiting for required data to appear. I can look further into it later today or tomorrow.

I could reproduce the broken info entry part with current masters of openpmix and prrte: https://github.com/openpmix/openpmix/issues/2644

**Comment by krempel-pt** [comment]
> > I do have an additional point: During my test attempts, I tried to pass `PMIX_GET_REFRESH_CACHE` info to the `PMIx_Get_nb()` call. I don't know whether the flag i already handled by openpmix, but it is passed to the host environment through `pmix_server_dmodex_req_fn_t`, too. What is that meant for? Shall the host do something here or just ignore that info entry? In the second case, wouldn't it be better to filter out such info entries and only pass those relevant for the host environment?
> > (Asking that here, since it fits into the topic headline, too)
> 
> When the remote host daemon passes the dmodex request to its PMIx server, the server returns _all_ the non-local (i.e., remote or global) data posted by the specified process. This is done for optimization since if someone asks for one piece of info about a process, it is likely they will be asking for other pieces of info from that process. So we send it all back.
> 
> Some programming models, however, involve a process re-posting a key at a later time in the execution, usually with a changed value. Since the "old" version of the key is already locally known, the client has to tell PMIx to "refresh the cache". True, we could edit that directive out of what they provided before up-calling the host, but we chose not to do so because the host environment might have chosen to keep their own cache of data they retrieved from the PMIx server. This simply informs the host that we really do want them to re-query their PMIx server for the data.
> 
> If you don't retain your own cache, then you can simply ignore that directive (which is what PRRTE does). Otherwise, there is no harm passing it down in the dmodex request to the local PMIx server - it'll just be ignored.

Alright, thanks again.

**Comment by jjhursey** [comment]
To drive this issue to completion. Is there a suggestion on a clarifying sentence or two for the standard?

**Comment by dsolt** [comment]
PR#484
