### ISSUE TITLE
What does PMIx mean by "ABI"?

### ISSUE THREAD

**Issue by rhc54** [pmix/pmix-standard#364]
This question arose while working with some folks at Fedora who were packaging OpenPMIx and developed into a somewhat far-reaching discussion. They use a particular ABI checker (https://lvc.github.io/abi-compliance-checker/) to verify ABI stability between versions of a package that have the same .so number. When running it against a couple of OpenPMIx versions, the program reported some ABI "changes" that precipitated the discussion.

My response eventually satisfied the immediate question, but I feel this merits a broader discussion and eventual adoption of a "standard" definition. The ABI currently consists of several elements:

* function APIs - pretty easy to tell ABI compatibility here, and the Standard already defines these
* numerical constants - the program checks to see if any have changed in value. RFC #359 should take care of it.
* structure membership, including relative positions of elements within the structure - the Standard defines these today
* macros - their program doesn't check these, but we have discussed how to handle them
* string attributes

It is the last item that sparked the majority of the discussion and likely requires some clarification in the Standard. The ABI checker specifically took exception to the addition of several PMIx attributes. My position was that "attributes" are _not_ part of the ABI because:

(a) the Standard requires that any implementation return "not supported" if it does not recognize a required attribute, though it is allowed to ignore a non-required attribute that it does not recognize

(b) as a result of (a), an application must always be prepared to deal with the return of a "not supported" response to any PMIx function call.

Thus, two versions of a library remain ABI compatible even though new attributes may have been added, or attributes may have been removed, because passing them to a library that doesn't recognize them has a clearly defined behavior/response. An application can therefore still dynamically use either version without problem - and this is the essence of "ABI compatibility".

We should decide if the community agrees with that understanding, or wishes to adopt some other definition.

**Comment by jjhursey** [comment]
I'm ok with some attributes being left out of the ABI. The required attributes should be in the ABI though - we should have some notation so users can distinguish between what is in the ABI and what is not.

**Comment by rhc54** [comment]
We'll have to kick it around - I find it hard to understand how a _string_ can be part of a _binary_ interface. I'm okay with specifying some attributes as required vs optional at the implementation level. I just can't grok how one defines an attribute as part of an ABI - seems logically inconsistent. APIs, structs, size of constants - these all have clear _binary_ implications, easy to understand them.

**Comment by jjhursey** [comment]
A few notes from the [Dec. 9, 2021 teleconf](https://github.com/pmix/pmix-standard/wiki/Meeting-2021-12-09) on this particular topic (please help me clarify):
 * There are two notions of an ABI in the software development community that we discussed:
   * "**Linker ABI**" A program build against Library A version 1 can link against Library A version 2 if the two are ABI compatible.
     * Note that the other way around (build against Library A version 2 can link against Library A version 1) is not covered since version 2 is allowed to add new symbols (e.g., functions), but cannot remove/modify the symbols.
     * This covers anything that impacts the symbols generated by the compiler when the library is created. This includes function signatures, data structures, fields in the data structures (ordering and naming), and sizes of data structures and fields.
     * Often libraries rely on [Semantic Versioning](https://semver.org/) to signify breaks in the Linker ABI.
   * "**Build ABI**" A program can build against Library A and link against Library B if the two are ABI compatible.
     * This requires **Linker ABI** and includes any constant values (and possibly code manipulations - macros) defined in the library headers used to build the program which are not represented as symbols in the shared library.
 * For the scenario of a "Build ABI":
   * This is helpful if you want to use LD_LIBRARY_PATH to swap out the libraries (some containerization models rely on this for, say, MPI compatibility). This is also helpful for tools that use `dlsym` to dynamically pick up the library and wire it into their application.
   * This assumes that all of the API in the header is part of the ABI in the generated library. However, constant values (be they integers or strings or ...) are not represented in the "Linker ABI" since they are not public symbols in the generated library but instead are represented in the header.
 * Some options:
   * If the PMIx Standard only supplies the Linker ABI then the tool & container use case is not fully covered.
   * If the PMIx Standard provides the Build ABI then is there any difference between the Standard and the ABI. Or worded differently, Is there anything we would define in the Standard that wouldn't be in the ABI?
   * In both of the above, implementations can choose to add new interfaces/symbols to their library and be ABI compatible. The application needs to be aware that if they use the "extra" interfaces (beyond the standard defined ABI) then they are no longer generating a "Build ABI" capable binary.

I'm sure I'm missing some details too, but maybe that'll help get the conversation going.

**Comment by jjhursey** [comment]
Per IAWG Meeting April 11, 2022:
 * The work to date has really targeted a **Build ABI** for the PMIx Standard, and that is reflected in the [pmix-abi](https://github.com/pmix/pmix-abi) repo. It defines the function symbols and the values of constants.
 * Suggestion was to add a short definition of both **Linker ABI** and **Build ABI** to the PMIx Standard. Highlight the use case for the PMIx Standard ABI is a **Build ABI** use case.

**Comment by jjhursey** [comment]
Added language to https://github.com/pmix/pmix-standard/pull/375
