### ISSUE TITLE
Clarify PMIx_Publish() return code during invalid data access

### ISSUE THREAD

**Issue by gvallee** [pmix/pmix-standard#41]
The current text says: ```Note that the keys must be unique within the specified data range or else an error will be returned (first published wins). ``` Would it be possible to specify the exact return code? Otherwise, users may wonder how to differentiate that case and an internal error.

**Comment by rhc54** [comment]
Hmmm...well, this is a bit of a pickle. The only one who has implemented support for this API is ORTE, and after reviewing that support (in light of this question), I find it is in fact wrong when dealing with multiply defined keys. ORTE actually stores and returns all of them, thus yielding multiple entries per key and violating the standard. ☹️ 

What we should do is define an error code for this specific issue - something like PMIX_ERR_DUPLICATE_KEY - but that means changing pmix_common.h, and so prior releases in the PMIx v2 series won't have that definition. I suspect that isn't acceptable.

Here is what I propose: we remove that sentence and replace it with an advice to users:
```
Duplicate keys within the specified data range may lead to unexpected behavior depending on host RM implementation of the backing key-value store. Future versions of the standard will clarify that a specific error be returned when conflicting values are published for a given key, and will provide attributes to allow modified behaviors such as overwrite
```
Since we already have a release of the library based on v3, we probably have to push the final repair to v4.

**Comment by jjhursey** [comment]
👍 on adding `PMIX_ERR_DUPLICATE_KEY` to the v4 interface.

Changing behavior in an errata for a standard (or in a point release for the PRI) seems troubling.
For v2 and v3, I like the idea of replacing the text with the following advice to users:
```
Duplicate keys within the specified data range may lead to unexpected behavior depending
on host RM implementation of the backing key-value store. 
```
Then an advice to implementors:
```
Implementations should, to the best of their ability, detect duplicate keys and protect the
user from unexpected behavior. Preferably they would return an error. This version of the
standard does not define a specific error code to be returned, so the implementation must
make it clear to the user what to expect in this scenario. One suggestion is to define an RM
specific error code above the \refconst{PMIX_EXTERNAL_ERR_BASE}. This scenario along 
with a specific error code will be provided in a future revision of the PMIx standard.
```

**Comment by rhc54** [comment]
👍  I'll make the mods as described.
